<?php

$artists = array(
    'Nadir Afonso',
    'Yaacov Agam',
    'Ellinor Aiki',
    'Josef Albers',
    'Pierre Alechinsky',
    'Nathan Altman',
    'Irving Amen',
    'Constantine Andreou',
    'Karel Appel',
    'Félix Arauz',
    'Alexander Archipenko',
    'Mino Argento',
    'Arman',
    'Jean Arp',
    'David Ascalon',
    'Frank Auerbach',
    'Edward Avedisian',
    'Milton Avery',
    'Alice Aycock',
    'Francis Bacon',
    'Giacomo Balla',
    'Balthus',
    'Vladimir Baranoff-Rossine',
    'Romare Bearden',
    'Max Beckmann',
    'George Bellows',
    'Thomas Hart Benton',
    'José Bernal',
    'Joseph Beuys',
    'Ralph Albert Blakelock',
    'Norman Bluhm',
    'Umberto Boccioni',
    'Alexander Bogomazov',
    'Pierre Bonnard',
    'Fernando Botero',
    'Louise Bourgeois',
    'Constantin Brâncuși',
    'Georges Braque',
    'Marcel Broodthaers',
    'James Brooks',
    'Joan Brown',
    'Daniel Buren',
    'David Burliuk',
    'Wladimir Burliuk',
    'Paul Cadmus',
    'Alexander Calder',
    'Josef Čapek',
    'Norman Carlberg',
    'Emily Carr',
    'Carlo Carrà',
    'Clarence Holbrook Carter',
    'Mary Cassatt',
    'Carlos Catasse',
    'Elizabeth Catlett',
    'Vija Celmins',
    'Paul Cézanne',
    'Marc Chagall',
    'John Chamberlain',
    'Giorgio de Chirico',
    'Dan Christensen',
    'Chuck Close',
    'Charles Conder',
    'Theo Constanté',
    'William Copley',
    'Joseph Cornell',
    'Tony Cragg',
    'Leon Dabo',
    'Salvador Dalí',
    'Gene Davis',
    'Ronald Davis',
    'Stuart Davis',
    'Lawrence Daws',
    'Michael J. Deas',
    'Edgar Degas',
    'Jay DeFeo',
    'Robert Delaunay',
    'Sonia Delaunay',
    'Charles Demuth',
    'André Derain',
    'Giorgio De Vincenzi',
    'Richard Diebenkorn',
    'Jim Dine',
    'Otto Dix',
    'Theo van Doesburg',
    'Jean Dubuffet',
    'Marcel Duchamp',
    'Elizabeth Durack',
    'Arthur Durston',
    'Friedel Dzubas',
    'Aleksandra Ekster',
    'James Ensor',
    'Max Ernst',
    'M. C. Escher',
    'Demetrios Farmakopoulos',
    'Paul Feeley',
    'Lyonel Feininger',
    'Pavel Filonov',
    'Sam Francis',
    'Jane Frank',
    'Helen Frankenthaler',
    'Lucian Freud',
    'Yitzhak Frenkel Frenel',
    'Fang Ganmin',
    'Wilhelmina Weber Furlong',
    'Naum Gabo',
    'Joaquín Torres García',
    'Enrico Garff',
    'Paul Gauguin',
    'Ilka Gedő',
    'Nina Genke-Meller',
    'Gunther Gerzso',
    'Alberto Giacometti',
    'Sam Gilliam',
    'William Glackens',
    'Vincent van Gogh',
    'Elias Goldberg',
    'Michael Goldberg',
    'Natalia Goncharova',
    'Robert Goodnough',
    'Arshile Gorky',
    'Józef Gosławski',
    'Adolph Gottlieb',
    'Nancy Graves',
    'Cleve Gray',
    'Balcomb Greene',
    'Stephen Greene',
    'Juan Gris',
    'Red Grooms',
    'George Grosz',
    'Oswaldo Guayasamín',
    'İsmet Güney',
    'Philip Guston',
    'Elaine Hamilton',
    'Richard Hamilton',
    'Duane Hanson',
    'Grace Hartigan',
    'Raoul Hausmann',
    'Michael Heizer',
    'Patrick Hennessy',
    'Barbara Hepworth',
    'Patrick Heron',
    'Eva Hesse',
    'Charles Hinman',
    'Hannah Höch',
    'David Hockney',
    'Howard Hodgkin',
    'Frances Hodgkins',
    'Hans Hofmann',
    'Edward Hopper',
    'Istvan Horkay',
    'Ralph Hotere',
    'John Hoyland',
    'Friedensreich Hundertwasser',
    'René Iché',
    'Leiko Ikemura',
    'Robert Indiana',
    'Augustus John',
    'Jasper Johns',
    'Ray Johnson',
    'Joan Jonas',
    'Asger Jorn',
    'Donald Judd',
    'Frida Kahlo',
    'Wolf Kahn',
    'Wassily Kandinsky',
    'Ellsworth Kelly',
    'Ernst Ludwig Kirchner',
    'Paul Klee',
    'Gustav Klimt',
    'Yves Klein',
    'Franz Kline',
    'Hilma af Klint',
    'Ivan Kliun',
    'Oskar Kokoschka',
    'Willem de Kooning',
    'Albert Kotin',
    'Lee Krasner',
    'Nicholas Krushenick',
    'František Kupka',
    'Kyung-hee Hong',
    'Wifredo Lam',
    'Ronnie Landfield',
    'John Latham',
    'Jacob Lawrence',
    'Fernand Léger',
    'Alfred Leslie',
    'Sol LeWitt',
    'Roy Lichtenstein',
    'Richard Lippold',
    'Charles Logasa',
    'Elfriede Lohse-Wächtler',
    'Morris Louis',
    'Lin Fengmian',
    'Stanton Macdonald-Wright',
    'August Macke',
    'Konrad Mägi',
    'René Magritte',
    'Aristide Maillol',
    'Kasimir Malevich',
    'Édouard Manet',
    'Robert Mangold',
    'Totte Mannes',
    'Piero Manzoni',
    'Franz Marc',
    'Conrad Marca-Relli',
    'Brice Marden',
    'Bruce McLean',
    'John Marin',
    'Marino Marini',
    'Chris Marker',
    'Agnes Martin',
    'Eugene J. Martin',
    'Knox Martin',
    'André Masson',
    'Henri Matisse',
    'Roberto Matta',
    'Gordon Matta-Clark',
    'Mikuláš Medek',
    'Vadim Meller',
    'Ana Mendieta',
    'Carlos Mérida',
    'Mario Merz',
    'Manolo Millares',
    'Joan Miró',
    'Joan Mitchell',
    'Stanley Matthew Mitruk',
    'Amedeo Modigliani',
    'László Moholy-Nagy',
    'Luis Molinari',
    'Piet Mondrian',
    'Claude Monet',
    'Henry Moore',
    'Giorgio Morandi',
    'Gustave Moreau',
    'Robert Motherwell',
    'Alfons Mucha',
    'Edvard Munch',
    'Bruce Nauman',
    'Manuel Neri',
    'G. P. Nerli',
    'Louise Nevelson',
    'Neith Nevelson',
    'Roy Newell',
    'Barnett Newman',
    'Alexander Ney',
    'Jan Nieuwenhuys',
    'Solomon Nikritin',
    'Isamu Noguchi',
    'Kenneth Noland',
    'Emil Nolde',
    'Brian ODoherty',
    'Georgia OKeeffe',
    'Claes Oldenburg',
    'Jules Olitski',
    'Nathan Oliveira',
    'Nam June Paik',
    'Niki de Saint Phalle',
    'Eduardo Paolozzi',
    'David Park',
    'Ray Parker',
    'George Passantino',
    'Waldo Peirce',
    'I. Rice Pereira',
    'Francis Picabia',
    'Pablo Picasso',
    'Jackson Pollock',
    'Larry Poons',
    'Liubov Popova',
    'Fuller Potter',
    'Richard Pousette-Dart',
    'Sughra Rababi',
    'Robert Rauschenberg',
    'Man Ray',
    'Kliment Redko',
    'Peter Reginato',
    'Ad Reinhardt',
    'Manuel Rendón',
    'Pierre-Auguste Renoir',
    'Bohuslav Reynek',
    'Gerhard Richter',
    'Bridget Riley',
    'Diego Rivera',
    'Manuel Rivera',
    'Alexander Rodchenko',
    'Auguste Rodin',
    'Nicholas Roerich',
    'Olga Rozanova',
    'James Rosenquist',
    'Mark Rothko',
    'Susan Rothenberg',
    'Henri Rousseau',
    'Edward Ruscha',
    'Albert Pinkham Ryder',
    'Egon Schiele',
    'Oskar Schlemmer',
    'Kurt Schwitters',
    'George Segal',
    'Richard Serra',
    'Pablo Serrano',
    'Georges-Pierre Seurat',
    'Ben Shahn',
    'Charles Sheeler',
    'Sally Sheinman',
    'Harry Shoulberg',
    'Paul Signac',
    'Josef Šíma',
    'David Simpson',
    'David Smith',
    'Tony Smith',
    'Robert Smithson',
    'Joan Snyder',
    'Chaïm Soutine',
    'Chaïm Soutine',
    'Václav Špála',
    'Austin Osman Spare',
    'Nicolas de Staël',
    'Theodoros Stamos',
    'Frank Stella',
    'Joseph Stella',
    'Hedda Sterne',
    'Clyfford Still',
    'Jindřich Štyrský',
    'Graham Sutherland',
    'Patrick Swift',
    'Tarsila do Amaral',
    'Enrique Tábara',
    'Atsuko Tanaka',
    'Dorothea Tanning',
    'Antoni Tàpies',
    'Vladimir Tatlin',
    'Paul Thek',
    'Wayne Thiebaud',
    'William Tillyer',
    'Jean Tinguely',
    'Alton Tobey',
    'Mark Tobey',
    'Bradley Walker Tomlin',
    'Toyen',
    'Richard Tuttle',
    'Cy Twombly',
    'Nadezhda Udaltsova',
    'Victor Vasarely',
    'Vladimír Vašíček',
    'Kuno Veeber',
    'Aníbal Villacís',
    'Juan Villafuerte',
    'Keratza Vissulceva',
    'Oswaldo Viteri',
    'Maurice de Vlaminck',
    'Marc Vaux',
    'Wolf Vostell',
    'Édouard Vuillard',
    'Andy Warhol',
    'Ilse Weber',
    'Tom Wesselmann',
    'Jan de Weryha-Wysoczanski',
    'James Abbott McNeill Whistler',
    'Thornton Willis',
    'Isaac Witkin',
    'Grant Wood',
    'Andrew Wyeth',
    'Xul Solar',
    'Taro Yamamoto',
    'Peter Young',
    'Larry Zox',
    'Jan Zrzavý',
    'Marina Abramović',
    'Vito Acconci',
    'Rita Ackermann',
    'Bas Jan Ader',
    'Eija-Liisa Ahtila',
    'Peggy Ahwesh',
    'Chantal Akerman',
    'Vikky Alexander',
    'Edward Allington',
    'Francis Alÿs',
    'El Anatsui',
    'Laurie Anderson',
    'Carl Andre',
    'Janine Antoni',
    'Ida Applebroog',
    'Nobuyoshi Araki',
    'Diane Arbus',
    'Siah Armajani',
    'Arman',
    'John Armleder',
    'Richard Artschwager',
    'Roy Ascott',
    'Frank Auerbach',
    'Sofia Areal',
    'Francis Bacon',
    'Jo Baer',
    'John Baldessari',
    'Balthus, ',
    'Banksy',
    'Fiona Banner',
    'Matthew Barney',
    'Will Barnet',
    'Artur Barrio',
    'Jennifer Bartlett',
    'Georg Baselitz',
    'Jean-Michel Basquiat',
    'Noah Becker, ',
    'Vanessa Beecroft',
    'Larry Bell',
    'Maurice Benayoun',
    'Lynda Benglis',
    'Danelle Bergstrom',
    'José Bernal',
    'Joseph Beuys',
    'Ashley Bickerton',
    'Janet Biggs',
    'Dara Birnbaum',
    'Ronald Bladen',
    'David Blatherwick',
    'Guy Bleus',
    'Christian Boltanski',
    'Alighiero Boëtti',
    'Maurizio Bolognini',
    'Henry Bond, ',
    'Christine Borland',
    'Michaël Borremans',
    'Eberhard Bosslet',
    'Fernando Botero',
    'Jack Boul, ',
    'Louise Bourgeois',
    'Mark Bradford',
    'Robert J Brawley',
    'Candice Breitz',
    'Stuart Brisley',
    'Marcel Broodthaers',
    'Glenn Brown',
    'Tania Bruguera',
    'Angela Bulloch',
    'Deborah Butterfield',
    'Chris Burden',
    'Jack Bush',
    'Gerard Byrne',
    'Sophie Calle',
    'Nuno de Campos',
    'Janet Cardiff',
    'Gerard Caris',
    'Norman Carlberg',
    'Gillian Carnegie',
    'Anthony Caro',
    'Antonio Caro',
    'Nicolas Carone',
    'James Casebere',
    'Maurizio Cattelan',
    'Nick Cave',
    'John Cederquist',
    'Vija Celmins', 
    'Saint Clair Cemin Brazilian',
    'John Chamberlain',
    'Suki Chan',  
    'Gordon Cheung',
    'Jake  Dinos Chapman', 
    'Judy Chicago',
    'Dan Christensen',
    'Dale Chihuly',
    'Abraham David Christia',
    'Chinwe Chukwuogo-Roy',  
    'Luke Ching',
    'Christo  Jeanne-Claud',
    'Paolo Cirio',
    'Lygia Clark',
    'Brian Clarke',
    'Francesco Clemente', 
    'Chuck Close',
    'Claude Closky',
    'Arnaud Cohen',
    'Robert Colescott', 
    'Mat Collishaw', 
    'George Condo', 
    'Cortis & Sonderegger', 
    'Tony Cragg',
    'Michael Craig-Martin',
    'Martin Creed',
    'Patricia Cronin',
    'José Luis Cuevas', 
    'Dado',
    'Hanne Darboven', 
    'Ian Davenport',   
    'Ronald Davis',
    'Richard Deacon', 
    'Tacita Dean', 
    'Wim Delvoye',
    'Walter De Maria', 
    'Abigail DeVille',
    'Guy Denning', 
    'Richard Diebenkorn', 
    'Rineke Dijkstra',
    'Sam Dillemans',
    'DOT DOT DOT', 
    'Braco Dimitrijevic',
    'Jim Dine', 
    'Mark di Suvero', 
    'Harry Dodge',
    'Peter Doig', 
    'Marlene Dumas', 
    'John Duncan',
    'Martin Eder',
    'Ólafur Elíasson',
    'Tracey Emin',
    'Ben Enwonwu',  
    'Bracha Ettinger',
    'Valie Export',
    'Mary Beth Edelson', 
    'Jan Fabre',
    'Öjvind Fahlström', 
    'Harun Farocki', 
    'Angus Fairhurst', 
    'Hans-Peter Feldmann', 
    'Kenneth Feingold', 
    'Brendan Fernandes', 
    'Teresita Fernández',
    'Esther Ferrer',  
    'Carole Feuerman', 
    'Stephen Finer', 
    'Eric Fischl',   
    'Peter Fischli & David Weiss',
    'Dan Flavin',
    'Bruno Fonseca', 
    'Caio Fonseca', 
    'Peter Forakis', 
    'Günther Förg',   
    'Sam Francis', 
    'Helen Frankenthaler', 
    'Andrea Fraser', 
    'Lucian Freud', 
    'Tom Friedman', 
    'Ellen Gallagher',
    'Anya Gallaccio',
    'Enrico Garff', 
    'Kendell Geers', 
    'Isa Genzken', 
    'Gilbert  George',  
    'Adrian Ghenie', 
    'Sam Gilliam', 
    'Liam Gillick', 
    'Karin Giusti', 
    'Robert Gober', 
    'Michael Goldberg', 
    'Nan Goldin', 
    'Jack Goldstein', 
    'Andy Goldsworthy', 
    'Peter Golfinopoulos', 
    'Leon Golub', 
    'Felix Gonzales-Torres', 
    'Dominique Gonzalez-Foerster',  
    'Robert Goodnough', 
    'Douglas Gordon',
    'Antony Gormley',
    'Dan Graham',
    'Robert Graham', 
    'Rodney Graham', 
    'Cleve Gray',
    'Kaloust Guedel', 
    'Genco Gulan',
    'Don Gummer',
    'Andreas Gursky',
    'Hans Haacke',
    'Jacques Halbert',
    'Petrit Halilaj',
    'David Hall',
    'Richard Hamilton',
    'Keith Haring',
    'Mona Hatoum',
    'Susan Hauptman',
    'Carl Michael von Hausswolff',
    'Tim Hawkinson, sculpture artist',
    'Al Held',
    'Gottfried Helnwein',
    'Diango Hernandez',
    'Jeremy Henderson',  
    'Eva Hesse',
    'Andreas Heusser', 
    'Hugo Heyrman',
    'Gary Hill',
    'Susan Hiller', 
    'Charles Hinman', 
    'Thomas Hirschhorn',
    'Damien Hirst',
    'David Hockney', 
    'Jim Hodges', 
    'Howard Hodgkin', 
    'Candida Höfer', 
    'Tom Holland', 
    'Frank Holliday',
    'Saskia Holmkvist', 
    'Christian Holstad', 
    'Jenny Holzer',
    'Roni Horn',   
    'Peter Howson', 
    'Teresa Hubbard/Alexander Birchler',  
    'Gary Hume',
    'Philipp Humm',
    'Pierre Huyghe',
    'Jörg Immendorff', 
    'INO',
    'Alfredo Jaar', 
    'Richard Jackson', 
    'Renata Jaworska', 
    'Chantal Joffe', 
    'Jasper Johns', 
    'Ray Johnson',
    'Jennie C. Jones',
    'Josignacio', 
    'Donald Judd', 
    'Isaac Julien', 
    'Ilya Kabakov',
    'Eduardo Kac',
    'Stanya Kahn', 
    'Wolf Kahn',
    'Anish Kapoor', 
    'Allan Kaprow', 
    'Deborah Kass',
    'On Kawara', 
    'Mary Kelly', 
    'Mike Kelley', 
    'Ellsworth Kelly', 
    'William Kentridge',  
    'Anselm Kiefer',
    'Manfred Kielnhofer',
    'Edward Kienholz', 
    'Karen Kilimnik', 
    'Bodys Isek Kingelez',
    'Martin Kippenberger', 
    'Komar Melamid', 
    'Jeff Koons', 
    'Mark Kostabi', 
    'Barbara Kruger',  
    'Alfred Freddy Krupa', 
    'Peter Kuckei', 
    'Yayoi Kusama', 
    'David LaChapelle', 
    'Suzanne Lacy',
    'Ronnie Landfield', 
    'Michael Landy', 
    'Thomas Lanigan-Schmidt',
    'Maria Lassnig', 
    'Matthieu Laurette', 
    'Robert Lazzarini', 
    'Lee Bul', 
    'Marc Lee',  
    'Zoe Leonard',
    'Mark Lewis',
    'Sol LeWitt',   
    'Richard Long', 
    'Robert Longo',   
    'Lee Lozano', 
    'Rafael Lozano-Hemmer', 
    'Sarah Lucas', 
    'Robert Mangold', 
    'Robert Mapplethorpe', 
    'Christian Marclay', 
    'Bruce McLean conceptual', 
    'Brice Marden', 
    'Kerry James Marshall', 
    'Milovan Destil Marković', 
    'Agnes Martin', 
    'Eugene J. Martin', 
    'Enrique Martinez Celaya',
    'Gordon Matta-Clark',
    'Amanda Matthews',
    'Paul McCarthy',  
    'Allan McCollum',
    'Ryan McGinley',
    'Steve McQueen',
    'Cildo Meireles',   
    'Ana Mendieta',  
    'Yucef Merhi', 
    'Thom Merrick',
    'Boris Mikhailov',
    'Ann Mikolowski, portrait miniaturist, waterscape',
    'Haroon Mirza',
    'Eva Moll',
    'Dianna Molzan',
    'Franco Mondini-Ruiz',
    'Jonathan Monk',
    'Sebastian Diaz Morales',
    'François Morellet',
    'Yasumasa Morimura',
    'Robert Morris',
    'Ed Moses',
    'Antoni Muntadas',
    'Vik Muniz',
    'Bruce Munro',
    'Takashi Murakami',
    'Elizabeth Murray',
    'Zoran Mušič',
    'Wangechi Mutu',
    'Bruce Nauman',
    'Ernesto Neto',
    'John Nieto',
    'Odd Nerdrum', 
    'Shirin Neshat',
    'NEVERCREW',
    'Alexander Ney',
    'Graham Nicholls',
    'Olaf Nicolai',
    'Kenneth Noland',
    'Thomas Nozkowski',
    'Jim Nutt',
    'Marina Núñez',
    'Albert Oehlen', 
    'Markus Oehlen',
    'Chris Ofili',
    'Georgia OKeeffe-1986)',
    'Claes Oldenburg-2022)',
    'Jules Olitski',
    'Nathan Oliveira',
    'Yoko Ono',
    'Bruce Onobrakpeya',   
    'Orlan',
    'Roman Opałka',
    'Catherine Opie',
    'Julian Opie',
    'Dennis Oppenheim',
    'Gabriel Orozco',
    'Tony Oursler, multimedia',
    'Nam June Paik',
    'Roxy Paine',
    'Eduardo Paolozzi',
    'Niki de Saint Phalle',
    'Cornelia Parker',
    'Ray Parker',
    'Ed Paschke',
    'Simon Patterson',
    'Oliver Payne',
    'Nick Relph',
    'Grayson Perry',
    'Raymond Pettibon',
    'Elizabeth Peyton',
    'Adrian Piper',
    'Steven Pippin', 
    'Michelangelo Pistoletto',
    'Lari Pittman',
    'Paola Pivi',
    'Sigmar Polke',
    'Larry Poons',
    'William Powhida',
    'Kenneth Price',
    'Richard Prince',   
    'Laure Prouvost',
    'Martin Puryear',
    'Marc Quinn',
    'Alessandro Raho',
    'Arnulf Rainer',
    'Yvonne Rainer',
    'Rallé',
    'Paul Henry Ramirez',
    'Neo Rauch',
    'Robert Rauschenberg',
    'Peter Reginato',
    'Paula Rego',
    'Seund Ja Rhee',
    'Jason Rhoades',  
    'Jesse Richards',
    'Gerhard Richter', 
    'Pipilotti Rist',
    'Larry Rivers',
    'James Rosenquist',
    'Martha Rosler', 
    'Dieter Roth',
    'Thomas Ruff',
    'Allen Ruppersberg',
    'Edward Ruscha',
    'Anri Sala',
    'Chéri Samba',
    'Jean-Michel Sanejouand',
    'David Salle',
    'Bojan Sarcevic',
    'Wilhelm Sasnal',
    'Jenny Saville',
    'Raymond Saunders',
    'Markus Schinwald',
    'Julian Schnabel',   
    'Carolee Schneemann',
    'Thomas Schütte',
    'Richard Serra',
    'Joel Shapiro',
    'Sonia Landy Sheridan',
    'Cindy Sherman',
    'Yinka Shonibare',
    'Amy Sillman',
    'David Simpson',
    'Lorna Simpson',
    'Bob  Roberta Smith',
    'Jack Smith',
    'Kiki Smith',
    'Robert Smithson',
    'Michael Snow', 
    'Joan Snyder',
    'Keith Sonnier',
    'Pierre Soulages',
    'Nancy Spero',
    'Joe Stefanelli',
    'Pat Steir',
    'Frank Stella',
    'Thomas Struth', 
    'Hiroshi Sugimoto',
    'Sarah Sze',
    'William Tillyer',
    'Tomoko Takahashi', 
    'Mark Tansey',
    'Sam Taylor-Wood',
    'Diana Thater',
    'Paul Thek', 
    'Wayne Thiebaud',
    'Hank Willis Thomas',
    'Arthur Thrall',
    'Agnes Thurnauer',
    'Wolfgang Tillmans',
    'Rirkrit Tiravanija', 
    'Mark Titchner',
    'Slaven Tolj',
    'Seb Toussaint',
    'Scott Treleaven',
    'Rosemarie Trockel',
    'Gavin Turk',
    'James Turrell',
    'Richard Tuttle',
    'Luc Tuymans',
    'Cy Twombly',
    'Keith Tyson',
    'Francis Upritchard',
    'Tomasz Urbanowicz',
    'Koen Vanmechelen', 
    'Lydia Venieri', 
    'Bill Viola',
    'Wolf Vostell',
    'Peter Voulkos',
    'Marc Vaux, conceptual',
    'Kara Walker',
    'Jeff Wall',
    'Magnus Wallin',
    'Mark Wallinger', 
    'Suling Wang',
    'Andy Warhol',
    'Gillian Wearing',
    'Carrie Mae Weems', 
    'Lawrence Weiner',
    'Monika Weiss', 
    'Ai Weiwei, Chinese',
    'Tom Wesselmann',
    'Franz West',
    'Rachel Whiteread',
    'Jack Whitten',
    'Alison Wilding',
    'Hannah Wilke',
    'Thornton Willis',
    'Jane  Louise Wilson',
    'Richard Wilson',
    'Joel-Peter Witkin',
    'Francesca Woodman',
    'Wu Guanzhong',
    'Erwin Wurm',
    'Andrew Wyeth',
    'Xing Xin',
    'Lynette Yiadom-Boakye',
    'Peter Young',
    'Jack Youngerman',
    'Andrea Zittel',
    'Larry Zox',
    'Ricardo Estanislao Zulueta',
    // digital artists
    'RULEBYART',
    'Milka Oxana',
    'Romain Trystram',
    'James Gilleard',
    'Alex Heywood',
    'David Sossella',
    'Ben Bauchau',
    'Antoni Tudisco',
    'Matt Schu',
    'Marija Tiurina',
    'Butcher Billy',
    'André Ducci',
    'Jinhwa Jang',
    'So Lazo',
    'MUTI',
    'Steve Simpson',
    'Beeple',
    'mbsjq',
    'Ori Toor',
    'The Rusted Pixel'


);

$i = random_int(1,855);


$result = $artists[$i];
echo $result;


?>