<?php

$text = array(
    'Marina Abramović',
    'Vito Acconci',
    'Rita Ackermann',
    'Bas Jan Ader',
    'Eija-Liisa Ahtila',
    'Peggy Ahwesh',
    'Chantal Akerman',
    'Vikky Alexander',
    'Edward Allington',
    'Francis Alÿs',
    'El Anatsui',
    'Laurie Anderson',
    'Carl Andre',
    'Janine Antoni',
    'Ida Applebroog',
    'Nobuyoshi Araki',
    'Diane Arbus',
    'Siah Armajani',
    'Arman',
    'John Armleder',
    'Richard Artschwager',
    'Roy Ascott',
    'Frank Auerbach',
    'Sofia Areal',
    'Francis Bacon',
    'Jo Baer',
    'John Baldessari',
    'Balthus, ',
    'Banksy',
    'Fiona Banner',
    'Matthew Barney',
    'Will Barnet',
    'Artur Barrio',
    'Jennifer Bartlett',
    'Georg Baselitz',
    'Jean-Michel Basquiat',
    'Noah Becker, ',
    'Vanessa Beecroft',
    'Larry Bell',
    'Maurice Benayoun',
    'Lynda Benglis',
    'Danelle Bergstrom',
    'José Bernal',
    'Joseph Beuys',
    'Ashley Bickerton',
    'Janet Biggs',
    'Dara Birnbaum',
    'Ronald Bladen',
    'David Blatherwick',
    'Guy Bleus',
    'Christian Boltanski',
    'Alighiero Boëtti',
    'Maurizio Bolognini',
    'Henry Bond, ',
    'Christine Borland',
    'Michaël Borremans',
    'Eberhard Bosslet',
    'Fernando Botero',
    'Jack Boul, ',
    'Louise Bourgeois',
    'Mark Bradford',
    'Robert J Brawley',
    'Candice Breitz',
    'Stuart Brisley',
    'Marcel Broodthaers',
    'Glenn Brown',
    'Tania Bruguera',
    'Angela Bulloch',
    'Deborah Butterfield',
    'Chris Burden',
    'Jack Bush',
    'Gerard Byrne',
    'Sophie Calle',
    'Nuno de Campos',
    'Janet Cardiff',
    'Gerard Caris',
    'Norman Carlberg',
    'Gillian Carnegie',
    'Anthony Caro',
    'Antonio Caro',
    'Nicolas Carone',
    'James Casebere',
    'Maurizio Cattelan',
    'Nick Cave',
    'John Cederquist',
    'Vija Celmins', 
    'Saint Clair Cemin Brazilian',
    'John Chamberlain',
    'Suki Chan',  
    'Gordon Cheung',
    'Jake  Dinos Chapman', 
    'Judy Chicago',
    'Dan Christensen',
    'Dale Chihuly',
    'Abraham David Christia',
    'Chinwe Chukwuogo-Roy',  
    'Luke Ching',
    'Christo  Jeanne-Claud',
    'Paolo Cirio',
    'Lygia Clark',
    'Brian Clarke',
    'Francesco Clemente', 
    'Chuck Close',
    'Claude Closky',
    'Arnaud Cohen',
    'Robert Colescott', 
    'Mat Collishaw', 
    'George Condo', 
    'Cortis & Sonderegger', 
    'Tony Cragg',
    'Michael Craig-Martin',
    'Martin Creed',
    'Patricia Cronin',
    'José Luis Cuevas', 
    'Dado',
    'Hanne Darboven', 
    'Ian Davenport',   
    'Ronald Davis',
    'Richard Deacon', 
    'Tacita Dean', 
    'Wim Delvoye',
    'Walter De Maria', 
    'Abigail DeVille',
    'Guy Denning', 
    'Richard Diebenkorn', 
    'Rineke Dijkstra',
    'Sam Dillemans',
    'DOT DOT DOT', 
    'Braco Dimitrijevic',
    'Jim Dine', 
    'Mark di Suvero', 
    'Harry Dodge',
    'Peter Doig', 
    'Marlene Dumas', 
    'John Duncan',
    'Martin Eder',
    'Ólafur Elíasson',
    'Tracey Emin',
    'Ben Enwonwu',  
    'Bracha Ettinger',
    'Valie Export',
    'Mary Beth Edelson', 
    'Jan Fabre',
    'Öjvind Fahlström', 
    'Harun Farocki', 
    'Angus Fairhurst', 
    'Hans-Peter Feldmann', 
    'Kenneth Feingold', 
    'Brendan Fernandes', 
    'Teresita Fernández',
    'Esther Ferrer',  
    'Carole Feuerman', 
    'Stephen Finer', 
    'Eric Fischl',   
    'Peter Fischli & David Weiss',
    'Dan Flavin',
    'Bruno Fonseca', 
    'Caio Fonseca', 
    'Peter Forakis', 
    'Günther Förg',   
    'Sam Francis', 
    'Helen Frankenthaler', 
    'Andrea Fraser', 
    'Lucian Freud', 
    'Tom Friedman', 
    'Ellen Gallagher',
    'Anya Gallaccio',
    'Enrico Garff', 
    'Kendell Geers', 
    'Isa Genzken', 
    'Gilbert  George',  
    'Adrian Ghenie', 
    'Sam Gilliam', 
    'Liam Gillick', 
    'Karin Giusti', 
    'Robert Gober', 
    'Michael Goldberg', 
    'Nan Goldin', 
    'Jack Goldstein', 
    'Andy Goldsworthy', 
    'Peter Golfinopoulos', 
    'Leon Golub', 
    'Felix Gonzales-Torres', 
    'Dominique Gonzalez-Foerster',  
    'Robert Goodnough', 
    'Douglas Gordon',
    'Antony Gormley',
    'Dan Graham',
    'Robert Graham', 
    'Rodney Graham', 
    'Cleve Gray',
    'Kaloust Guedel', 
    'Genco Gulan',
    'Don Gummer',
    'Andreas Gursky',
    'Hans Haacke',
    'Jacques Halbert',
    'Petrit Halilaj',
    'David Hall',
    'Richard Hamilton',
    'Keith Haring',
    'Mona Hatoum',
    'Susan Hauptman',
    'Carl Michael von Hausswolff',
    'Tim Hawkinson, sculpture artist',
    'Al Held',
    'Gottfried Helnwein',
    'Diango Hernandez',
    'Jeremy Henderson',  
    'Eva Hesse',
    'Andreas Heusser', 
    'Hugo Heyrman',
    'Gary Hill',
    'Susan Hiller', 
    'Charles Hinman', 
    'Thomas Hirschhorn',
    'Damien Hirst',
    'David Hockney', 
    'Jim Hodges', 
    'Howard Hodgkin', 
    'Candida Höfer', 
    'Tom Holland', 
    'Frank Holliday',
    'Saskia Holmkvist', 
    'Christian Holstad', 
    'Jenny Holzer',
    'Roni Horn',   
    'Peter Howson', 
    'Teresa Hubbard/Alexander Birchler',  
    'Gary Hume',
    'Philipp Humm',
    'Pierre Huyghe',
    'Jörg Immendorff', 
    'INO',
    'Alfredo Jaar', 
    'Richard Jackson', 
    'Renata Jaworska', 
    'Chantal Joffe', 
    'Jasper Johns', 
    'Ray Johnson',
    'Jennie C. Jones',
    'Josignacio', 
    'Donald Judd', 
    'Isaac Julien', 
    'Ilya Kabakov',
    'Eduardo Kac',
    'Stanya Kahn', 
    'Wolf Kahn',
    'Anish Kapoor', 
    'Allan Kaprow', 
    'Deborah Kass',
    'On Kawara', 
    'Mary Kelly', 
    'Mike Kelley', 
    'Ellsworth Kelly', 
    'William Kentridge',  
    'Anselm Kiefer',
    'Manfred Kielnhofer',
    'Edward Kienholz', 
    'Karen Kilimnik', 
    'Bodys Isek Kingelez',
    'Martin Kippenberger', 
    'Komar Melamid', 
    'Jeff Koons', 
    'Mark Kostabi', 
    'Barbara Kruger',  
    'Alfred Freddy Krupa', 
    'Peter Kuckei', 
    'Yayoi Kusama', 
    'David LaChapelle', 
    'Suzanne Lacy',
    'Ronnie Landfield', 
    'Michael Landy', 
    'Thomas Lanigan-Schmidt',
    'Maria Lassnig', 
    'Matthieu Laurette', 
    'Robert Lazzarini', 
    'Lee Bul', 
    'Marc Lee',  
    'Zoe Leonard',
    'Mark Lewis',
    'Sol LeWitt',   
    'Richard Long', 
    'Robert Longo',   
    'Lee Lozano', 
    'Rafael Lozano-Hemmer', 
    'Sarah Lucas', 
    'Robert Mangold', 
    'Robert Mapplethorpe', 
    'Christian Marclay', 
    'Bruce McLean conceptual', 
    'Brice Marden', 
    'Kerry James Marshall', 
    'Milovan Destil Marković', 
    'Agnes Martin', 
    'Eugene J. Martin', 
    'Enrique Martinez Celaya',
    'Gordon Matta-Clark',
    'Amanda Matthews',
    'Paul McCarthy',  
    'Allan McCollum',
    'Ryan McGinley',
    'Steve McQueen',
    'Cildo Meireles',   
    'Ana Mendieta',  
    'Yucef Merhi', 
    'Thom Merrick',
    'Boris Mikhailov',
    'Ann Mikolowski, portrait miniaturist, waterscape',
    'Haroon Mirza',
    'Eva Moll',
    'Dianna Molzan',
    'Franco Mondini-Ruiz',
    'Jonathan Monk',
    'Sebastian Diaz Morales',
    'François Morellet',
    'Yasumasa Morimura',
    'Robert Morris',
    'Ed Moses',
    'Antoni Muntadas',
    'Vik Muniz',
    'Bruce Munro',
    'Takashi Murakami',
    'Elizabeth Murray',
    'Zoran Mušič',
    'Wangechi Mutu',
    'Bruce Nauman',
    'Ernesto Neto',
    'John Nieto',
    'Odd Nerdrum', 
    'Shirin Neshat',
    'NEVERCREW',
    'Alexander Ney',
    'Graham Nicholls',
    'Olaf Nicolai',
    'Kenneth Noland',
    'Thomas Nozkowski',
    'Jim Nutt',
    'Marina Núñez',
    'Albert Oehlen', 
    'Markus Oehlen',
    'Chris Ofili',
    'Georgia OKeeffe-1986)',
    'Claes Oldenburg-2022)',
    'Jules Olitski',
    'Nathan Oliveira',
    'Yoko Ono',
    'Bruce Onobrakpeya',   
    'Orlan',
    'Roman Opałka',
    'Catherine Opie',
    'Julian Opie',
    'Dennis Oppenheim',
    'Gabriel Orozco',
    'Tony Oursler, multimedia',
    'Nam June Paik',
    'Roxy Paine',
    'Eduardo Paolozzi',
    'Niki de Saint Phalle',
    'Cornelia Parker',
    'Ray Parker',
    'Ed Paschke',
    'Simon Patterson',
    'Oliver Payne',
    'Nick Relph',
    'Grayson Perry',
    'Raymond Pettibon',
    'Elizabeth Peyton',
    'Adrian Piper',
    'Steven Pippin', 
    'Michelangelo Pistoletto',
    'Lari Pittman',
    'Paola Pivi',
    'Sigmar Polke',
    'Larry Poons',
    'William Powhida',
    'Kenneth Price',
    'Richard Prince',   
    'Laure Prouvost',
    'Martin Puryear',
    'Marc Quinn',
    'Alessandro Raho',
    'Arnulf Rainer',
    'Yvonne Rainer',
    'Rallé',
    'Paul Henry Ramirez',
    'Neo Rauch',
    'Robert Rauschenberg',
    'Peter Reginato',
    'Paula Rego',
    'Seund Ja Rhee',
    'Jason Rhoades',  
    'Jesse Richards',
    'Gerhard Richter', 
    'Pipilotti Rist',
    'Larry Rivers',
    'James Rosenquist',
    'Martha Rosler', 
    'Dieter Roth',
    'Thomas Ruff',
    'Allen Ruppersberg',
    'Edward Ruscha',
    'Anri Sala',
    'Chéri Samba',
    'Jean-Michel Sanejouand',
    'David Salle',
    'Bojan Sarcevic',
    'Wilhelm Sasnal',
    'Jenny Saville',
    'Raymond Saunders',
    'Markus Schinwald',
    'Julian Schnabel',   
    'Carolee Schneemann',
    'Thomas Schütte',
    'Richard Serra',
    'Joel Shapiro',
    'Sonia Landy Sheridan',
    'Cindy Sherman',
    'Yinka Shonibare',
    'Amy Sillman',
    'David Simpson',
    'Lorna Simpson',
    'Bob  Roberta Smith',
    'Jack Smith',
    'Kiki Smith',
    'Robert Smithson',
    'Michael Snow', 
    'Joan Snyder',
    'Keith Sonnier',
    'Pierre Soulages',
    'Nancy Spero',
    'Joe Stefanelli',
    'Pat Steir',
    'Frank Stella',
    'Thomas Struth', 
    'Hiroshi Sugimoto',
    'Sarah Sze',
    'William Tillyer',
    'Tomoko Takahashi', 
    'Mark Tansey',
    'Sam Taylor-Wood',
    'Diana Thater',
    'Paul Thek', 
    'Wayne Thiebaud',
    'Hank Willis Thomas',
    'Arthur Thrall',
    'Agnes Thurnauer',
    'Wolfgang Tillmans',
    'Rirkrit Tiravanija', 
    'Mark Titchner',
    'Slaven Tolj',
    'Seb Toussaint',
    'Scott Treleaven',
    'Rosemarie Trockel',
    'Gavin Turk',
    'James Turrell',
    'Richard Tuttle',
    'Luc Tuymans',
    'Cy Twombly',
    'Keith Tyson',
    'Francis Upritchard',
    'Tomasz Urbanowicz',
    'Koen Vanmechelen', 
    'Lydia Venieri', 
    'Bill Viola',
    'Wolf Vostell',
    'Peter Voulkos',
    'Marc Vaux, conceptual',
    'Kara Walker',
    'Jeff Wall',
    'Magnus Wallin',
    'Mark Wallinger', 
    'Suling Wang',
    'Andy Warhol',
    'Gillian Wearing',
    'Carrie Mae Weems', 
    'Lawrence Weiner',
    'Monika Weiss', 
    'Ai Weiwei, Chinese',
    'Tom Wesselmann',
    'Franz West',
    'Rachel Whiteread',
    'Jack Whitten',
    'Alison Wilding',
    'Hannah Wilke',
    'Thornton Willis',
    'Jane  Louise Wilson',
    'Richard Wilson',
    'Joel-Peter Witkin',
    'Francesca Woodman',
    'Wu Guanzhong',
    'Erwin Wurm',
    'Andrew Wyeth',
    'Xing Xin',
    'Lynette Yiadom-Boakye',
    'Peter Young',
    'Jack Youngerman',
    'Andrea Zittel',
    'Larry Zox',
    'Ricardo Estanislao Zulueta

";








$pattern ='/\s*\([0-9]{4}\)?|\s*–[0-9]{4}\)/';
// Loop through each line  extract the name  remove the date
foreach (explode("\n", $text) as $line) {
    $name = trim(preg_replace($pattern, '', $line));
    
    // Check if the name is not empty
    if (!empty($name)) {
//        echo $name . "\n";
    }

    $pattern1 = '/ \(born\s+\d{4}\)/';
    $result = preg_replace($pattern1, '', $name);
    echo $result  . "\n"; // Output: Erwin Wurm, , 
}


?>

1   










